[package]
edition = "2021"
name = "plugin-dylib"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plugin = {path = "../plugin"}
plugin-dylib-api = {path = "../plugin-dylib-api/"}
